version: "3.8"
services:
    web:
        image: hristodinev123/docker-web
        deploy:
            replicas: 5
        ports:
            - 8080:80
        volumes:
         - type:bind
           source: /home/vagrant/docker-demo/web
           target: /var/www/html
           read_only: true
           bind:
             create_host_path: true
        networks:
            - app-network
    db:
        image: shekeriev/docker-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: 12345
networks:
    app-network:
